#!/usr/bin/env python3

import functools
import json
import subprocess
import os.path
import sys

from shlex import quote

THISDIR = os.path.dirname(os.path.abspath(__file__))
XPM_PATH = os.path.join(THISDIR, 'imported/tw-l-15.xpm')
FOREVER = os.path.join(THISDIR, 'bin/forever')
del THISDIR
PROGNAME = os.path.basename(sys.argv[0])
TASK = 'task' # path to the task binary
TMUX = 'tmux' # path to the tmux binary

@functools.lru_cache(maxsize=1)
def taskdir():
    "Return `task show data.location`."
    output = subprocess.check_output(['task', '_show'])
    lines = output.decode('UTF-8').splitlines()
    prefix = 'data.location='
    for line in lines:
        if line.startswith(prefix):
            return os.path.expanduser(line[len(prefix):].rstrip('\n'))
    else:
        assert False, "`task _show` did not report data.location"
LOCK_FILENAME = os.path.join(taskdir(), ".taskswamp.lock")
LOCK_TIMEOUT = 5 # seconds


## Library

def execve_to_system(args):
    """Given an execve()-style array representing a command to be executed,
    return a system()-style string representing the same command."""
    return ' '.join(map(quote, args))

def tmux_session_exists(sessionname):
    "Return TRUE if a tmux session SESSIONNAME is running."
    return sessionname in set(
        subprocess.check_output([TMUX, 'list-sessions', '-F', '#S']).decode().splitlines()
    )


## Data model

class TmuxWindow:
    """Encapsulates the configuration for a single tmux window."""

    # self.cmd (string): comand to be executed
    # self.name (string): the window title
    def __init__(self, jsonobj, refresh_every):

        # Set self.name
        self.name = jsonobj['name']

        # Set self.cmd
        if 'task' in jsonobj:
            cmd = ' '.join([FOREVER,
                            str(refresh_every),
                            'flock', '-x', '-w', str(LOCK_TIMEOUT), LOCK_FILENAME,
                            TASK, jsonobj['task']])
        else:
            cmd = jsonobj['cmd']
        if type(cmd) == type([]):
            self.cmd = execve_to_system(cmd)
        elif type(cmd) == type(''):
            self.cmd = cmd
        assert hasattr(self, 'cmd'), \
          "Invalid configuration: no 'task' or 'cmd' key in %r" % (jsonobj,)


##

def main():
    ## Read the config file.
    try:
        with open(os.path.expanduser('~/.taskswamprc')) as fd:
            config = json.load(fd)
    except FileNotFoundError:
        sys.exit("{}: ~/.taskswamprc file not found; see README for instructions.".format(PROGNAME))

    assert config['taskswamp'] == -1, "Missing config format number"

    refresh_every = config.get('refresh_every', "0")
    try:
        refresh_every = float(refresh_every)
        assert refresh_every >= 0, \
          "Invalid configuration: refresh_every can't be negative"
    except ValueError:
        assert False, \
          "Invalid configuration: refresh_every is not a numerical value"

    ## Parse it.
    sessionname = config.get('sessionname', "task")
    windows = tuple(TmuxWindow(jsonobj, refresh_every) for jsonobj in config['windows'])

    ## Prepare the tmux session- and window-creation commands.
    # The first window is part of the 'new-session' command.
    window_cmds = [['new-window', '-d', '-n', w.name, w.cmd] for w in windows]
    window_cmds[0][:2] = ['new-session', '-s', sessionname]
    del windows
    #del sessionname

    # This is a list of lists; each internal list is a single tmux command
    tmux_cmds = []
    tmux_cmds += [['set-option', '-g', 'set-remain-on-exit', 'on']]
    tmux_cmds += window_cmds
    del window_cmds

    ## Launch tmux, creating the session or attaching to it.
    if tmux_session_exists(sessionname):
        args = [TMUX, 'attach-session', '-t', sessionname]
    else:
        args = [TMUX] + sum((cmd+[';'] for cmd in tmux_cmds), [])
    args = [
        'xterm',
        '-xrm', 'XTerm*iconHint: {}'.format(XPM_PATH),
        '-T', sessionname,
        '-n', sessionname,
    ] + ['-e'] + args
    subprocess.check_call(args)

if __name__ == '__main__':
    main()
